### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by arnarleifs** [rebus-org/Rebus.NLog#1]
Why isn't there any documentation provided for this extension?

**Comment by mookid8000** [comment]
Mostly because noone has asked for it. Is there anything in particular you are curious about?

**Comment by arnarleifs** [comment]
I see. Just a general documentation on how it's used. Nothing particular yet.

**Comment by mookid8000** [comment]
I updated [the readme](https://github.com/rebus-org/Rebus.NLog/blob/master/README.md) to show how you incorporate Rebus.NLog into your ordinary Rebus configuration.

Please let me know if there's anything more you feel is missing 😄
