### ISSUE TITLE
Rebus.NLog uses a version of NLog that doesn't exist

### ISSUE THREAD

**Issue by donig** [rebus-org/Rebus.NLog#2]
Rebus.NLog has a reference to NLog >= 5.0.0-beta06, but there are no matching NuGet packages. The 4.5 branches are the current latest.

**Comment by mookid8000** [comment]
wow that's crazy! – I wonder how that could have happened..... I'll look at it right away

**Comment by mookid8000** [comment]
NLog 5.0.0-beta06 must have existed on NuGet.org 10 months ago when I ported this library to the new project structure.

I'll revert it back to 4.5.0-rc04, which seems to be the latest version right now.

**Comment by mookid8000** [comment]
I've released a fix as Rebus.NLog 4.0.1 – I figured it wasn't a breaking change because 4.0.0 was broken anyway.

Thanks for reporting this 👍
